In [54]:
import numpy as np
import pandas as pd

Question 1
What's the version of Pandas that you installed?

In [55]:
pd.__version__

'1.4.3'

In [ ]:
!curl https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv
df_ch = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv')

In [57]:
df_ch.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY

Question 2
How many columns are in the dataset?

10
6560
10989
20640

In [58]:
df_ch.shape[1]

10

Question 3: Select columns with missing data

'total_rooms'
'total_bedrooms'
both of the above
no empty columns in the dataset

In [59]:
df_ch.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

Question 4: Number of unique values in the 'ocean_proximity' column

In [60]:
df_ch['ocean_proximity'].nunique()

5

Question 5: Average value of the 'median_house_value' for the houses near the bay

In [61]:
df_ch.groupby('ocean_proximity').median_house_value.mean()

ocean_proximity
<1H OCEAN     240084.285464
INLAND        124805.392001
ISLAND        380440.000000
NEAR BAY      259212.311790
NEAR OCEAN    249433.977427
Name: median_house_value, dtype: float64

In [62]:
df_ch.groupby(df_ch.ocean_proximity == 'NEAR BAY').median_house_value.mean()

ocean_proximity
False    200321.954605
True     259212.311790
Name: median_house_value, dtype: float64

In [43]:
df_ch[df_ch['ocean_proximity'] == 'NEAR BAY'].groupby('ocean_proximity').median_house_value.mean()

ocean_proximity
NEAR BAY    259212.31179
Name: median_house_value, dtype: float64

Question 6: Has the mean value changed after filling missing values?

In [63]:
df_ch_f = df_ch
mean_value = df_ch_f['total_bedrooms'].mean()
mean_value

537.8705525375618

In [64]:
df_ch_f.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

In [65]:
df_ch_f['total_bedrooms'].fillna(value=mean_value, inplace = True)

In [66]:
df_ch_f.isnull().sum()

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
median_house_value    0
ocean_proximity       0
dtype: int64

In [67]:
mean_value = df_ch_f['total_bedrooms'].mean()
mean_value

537.8705525375639

Questions 7: Value of the last element of w

In [69]:
island_df = df_ch[df_ch['ocean_proximity'] == 'ISLAND']
island_df.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
8314    -118.32     33.35                27.0       1675.0           521.0   
8315    -118.33     33.34                52.0       2359.0           591.0   
8316    -118.32     33.33                52.0       2127.0           512.0   
8317    -118.32     33.34                52.0        996.0           264.0   
8318    -118.48     33.43                29.0        716.0           214.0   

      population  households  median_income  median_house_value  \
8314       744.0       331.0         2.1579            450000.0   
8315      1100.0       431.0         2.8333            414700.0   
8316       733.0       288.0         3.3906            300000.0   
8317       341.0       160.0         2.7361            450000.0   
8318       422.0       173.0         2.6042            287500.0   

     ocean_proximity  
8314          ISLAND  
8315          ISLAND  
8316          ISLAND  
8317          ISLAND  
8318          ISLAND

In [70]:
island_df = island_df[['housing_median_age', 'total_rooms', 'total_bedrooms']]
island_df.head()

housing_median_age  total_rooms  total_bedrooms
8314                27.0       1675.0           521.0
8315                52.0       2359.0           591.0
8316                52.0       2127.0           512.0
8317                52.0        996.0           264.0
8318                29.0        716.0           214.0

In [74]:
X = island_df.to_numpy()
X

array([[  27., 1675.,  521.],
       [  52., 2359.,  591.],
       [  52., 2127.,  512.],
       [  52.,  996.,  264.],
       [  29.,  716.,  214.]])

In [75]:
XTX = X.T @ X
XTX

array([[9.6820000e+03, 3.5105300e+05, 9.1357000e+04],
       [3.5105300e+05, 1.4399307e+07, 3.7720360e+06],
       [9.1357000e+04, 3.7720360e+06, 9.9835800e+05]])

In [76]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 9.19403586e-04, -3.66412216e-05,  5.43072261e-05],
       [-3.66412216e-05,  8.23303633e-06, -2.77534485e-05],
       [ 5.43072261e-05, -2.77534485e-05,  1.00891325e-04]])

In [77]:
y = np.array([950, 1300, 800, 1000, 1300])

In [78]:
w = (XTX_inv @ X.T) @ y
w

array([23.12330961, -1.48124183,  5.69922946])

In [79]:
w[-1]

5.699229455065575